on: push

jobs:
  build-php:
    runs-on: ubuntu-latest
    container: php:8.2-cli

    steps:
      - run: echo "TESTING"
      - run: php --version
      - uses: actions/checkout@v3
      - run: php app.php